name:                store-graph
version:             0.1.0.0
github:              "githubuser/store-graph"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md
- test/store/*.drv

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/store-graph#readme>


dependencies:
- base >= 4.7 && < 5
- directory
- strict
- regex-posix
- nix-derivation
- bytestring
- text
- attoparsec
- containers
- system-filepath
- filepath
- graphviz
- cassava
- vector
- regex-tdfa

library:
  source-dirs: src

default-extensions:
  - QuasiQuotes

executables:
  store-graph-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - store-graph

tests:
  store-graph-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - store-graph
    - hspec
